/**
 * UI \ [99] — Official Registry & Component Catalog (99 Standard Elements)
 * Modeled after shadcn/ui and Linear design systems with WCAG 2.2 AAA certification.
 */

export interface ComponentPropDoc {
  name: string;
  type: string;
  default?: string;
  description: string;
}

export interface ComponentRegistryItem {
  id: string;
  name: string;
  title: string;
  description: string;
  category: 'Actions' | 'Forms' | 'Selection' | 'Data Display' | 'Overlays' | 'Layout & Navigation';
  version: string;
  primitive?: string;
  dependencies: string[];
  devDependencies?: string[];
  registryDependencies?: string[];
  cliCommand: string;
  usageSnippet: string;
  codeSnippet: string;
  props: ComponentPropDoc[];
  features: string[];
}

export const REGISTRY_COMPONENTS: ComponentRegistryItem[] = [
  // ──────────────────────────────
  // 1. ACTIONS & BUTTONS (10 Elements)
  // ──────────────────────────────
  {
    id: 'button',
    name: 'button',
    title: 'Button',
    description: 'Displays a button with Obsidian velvet depth, specular rim highlight, and responsive spring physics.',
    category: 'Actions',
    version: '1.0.0',
    primitive: 'Native button / Radix Slot',
    dependencies: ['class-variance-authority', 'clsx', 'tailwind-merge', 'lucide-react'],
    cliCommand: 'npx @99/ui add button',
    features: ['5 visual variants', '4 responsive size tiers', 'Specular rim highlight', 'Active scale feedback', 'Accessible WCAG AAA contrast'],
    usageSnippet: `import { Button } from "@99/ui"\n\nexport default function Demo() {\n  return <Button variant="primary">Create Project</Button>\n}`,
    codeSnippet: `export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>((props, ref) => <button ref={ref} {...props} />);`,
    props: [
      { name: 'variant', type: "'primary' | 'secondary' | 'outline' | 'ghost' | 'rose'", default: "'primary'", description: 'Visual hierarchy.' },
      { name: 'size', type: "'xs' | 'sm' | 'md' | 'lg'", default: "'md'", description: 'Padding and touch target size.' },
      { name: 'loading', type: 'boolean', default: 'false', description: 'Shows animated loading spinner.' },
    ],
  },
  {
    id: 'icon-button',
    name: 'icon-button',
    title: 'Icon Button',
    description: 'Touch-calibrated square or circular icon action button with built-in hit area proxy for mobile.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add icon-button',
    features: ['Min 44px hit-target', 'Specular rim highlight', 'Hover state layer', 'Active spring press'],
    usageSnippet: `import { IconButton } from "@99/ui"\nimport { Plus } from "lucide-react"\n\n<IconButton icon={<Plus />} aria-label="Add item" />`,
    codeSnippet: `export const IconButton = ({ icon, ...props }) => <Button size="sm" className="p-2" {...props}>{icon}</Button>;`,
    props: [{ name: 'icon', type: 'ReactNode', description: 'Icon component to display inside button.' }],
  },
  {
    id: 'copy-button',
    name: 'copy-button',
    title: 'Copy Button',
    description: 'One-click clipboard copy button with transient animated checkmark and sound/haptic hook.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add copy-button',
    features: ['Instant clipboard write', '2s check feedback', 'Aria-live announcement'],
    usageSnippet: `import { CopyButton } from "@99/ui"\n\n<CopyButton text="npm i @99/ui" />`,
    codeSnippet: `export const CopyButton = ({ text }) => { /* Copy with state */ };`,
    props: [{ name: 'text', type: 'string', description: 'Target string copied to clipboard.' }],
  },
  {
    id: 'toggle',
    name: 'toggle',
    title: 'Toggle',
    description: 'A two-state button that can be either on or off, with tactile pressed feedback.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-toggle'],
    cliCommand: 'npx @99/ui add toggle',
    features: ['Radix state primitive', 'Specular rim outline', 'Keyboard Space/Enter toggle'],
    usageSnippet: `import { Toggle } from "@99/ui"\nimport { Bold } from "lucide-react"\n\n<Toggle aria-label="Toggle bold"><Bold className="w-4 h-4" /></Toggle>`,
    codeSnippet: `export const Toggle = RadixToggle.Root;`,
    props: [{ name: 'pressed', type: 'boolean', description: 'Controlled pressed state.' }],
  },
  {
    id: 'toggle-group',
    name: 'toggle-group',
    title: 'Toggle Group',
    description: 'A set of two-state buttons that can be toggled on or off together in single or multiple modes.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-toggle-group'],
    cliCommand: 'npx @99/ui add toggle-group',
    features: ['Single or multi-select', 'Roving focus tabindex', 'RTL keyboard arrow support'],
    usageSnippet: `import { ToggleGroup, ToggleGroupItem } from "@99/ui"\n\n<ToggleGroup type="single"><ToggleGroupItem value="left">L</ToggleGroupItem></ToggleGroup>`,
    codeSnippet: `export const ToggleGroup = RadixToggleGroup.Root;`,
    props: [{ name: 'type', type: "'single' | 'multiple'", description: 'Selection mode.' }],
  },
  {
    id: 'tag',
    name: 'tag',
    title: 'Tag & Chip',
    description: 'Interactive removable label capsules with calibrated palette colors and hit-area remove triggers.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add tag',
    features: ['6 semantic colorways', 'Optional onRemove button', 'Accessible badge role'],
    usageSnippet: `import { Tag } from "@99/ui"\n\n<Tag variant="purple" onRemove={() => {}}>Design System</Tag>`,
    codeSnippet: `export const Tag = ({ variant, onRemove, children }) => <span>{children}</span>;`,
    props: [{ name: 'variant', type: "'neutral' | 'emerald' | 'blue' | 'purple' | 'amber' | 'rose'", description: 'Color style.' }],
  },
  {
    id: 'kbd',
    name: 'kbd',
    title: 'Kbd',
    description: 'Displays keyboard keys and shortcuts in Linear style with monospaced typography and specular borders.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add kbd',
    features: ['Pixel-perfect 18px height', 'Double specular border', 'JetBrains Mono font'],
    usageSnippet: `import { Kbd } from "@99/ui"\n\n<Kbd>⌘K</Kbd>`,
    codeSnippet: `export const Kbd = ({ children }) => <kbd className="px-1.5 py-0.5 font-mono text-xs">{children}</kbd>;`,
    props: [{ name: 'size', type: "'xs' | 'sm' | 'md'", description: 'Size tier.' }],
  },
  {
    id: 'avatar',
    name: 'avatar',
    title: 'Avatar',
    description: 'User profile image element with fallback initials and obsidian ring border.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-avatar'],
    cliCommand: 'npx @99/ui add avatar',
    features: ['Image lazy loading', 'Automatic initial fallback', 'Ring contrast separation'],
    usageSnippet: `import { Avatar } from "@99/ui"\n\n<Avatar src="/user.jpg" fallback="JD" />`,
    codeSnippet: `export const Avatar = ({ src, fallback }) => <div>{fallback}</div>;`,
    props: [{ name: 'fallback', type: 'string', description: 'Letters displayed if image fails.' }],
  },
  {
    id: 'avatar-stack',
    name: 'avatar-stack',
    title: 'Avatar Stack',
    description: 'Overlapping grouped team members with negative margin and overflow count pill.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add avatar-stack',
    features: ['Configurable max display', '+N remaining counter', 'Concentric border cutout'],
    usageSnippet: `import { AvatarStack } from "@99/ui"\n\n<AvatarStack users={[{ name: 'Alex' }, { name: 'Sarah' }]} max={3} />`,
    codeSnippet: `export const AvatarStack = ({ users, max = 3 }) => <div>...</div>;`,
    props: [{ name: 'max', type: 'number', description: 'Maximum visible avatars.' }],
  },
  {
    id: 'swatch',
    name: 'swatch',
    title: 'Color Swatch',
    description: 'Token color chip visualizing chromatic values with one-click hex copying.',
    category: 'Actions',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add swatch',
    features: ['Checkerboard transparency bg', 'Tooltip hex info', 'Copy on click'],
    usageSnippet: `import { Swatch } from "@99/ui"\n\n<Swatch color="#10B981" name="Emerald" />`,
    codeSnippet: `export const Swatch = ({ color, name }) => <button style={{ backgroundColor: color }} />;`,
    props: [{ name: 'color', type: 'string', description: 'Hex or RGB color code.' }],
  },

  // ──────────────────────────────
  // 2. FORM CONTROLS & ADVANCED INPUTS (20 Elements)
  // ──────────────────────────────
  {
    id: 'input',
    name: 'input',
    title: 'Input',
    description: 'Single-line text input field with left/right icon slots, clear button, and accessible validation states.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add input',
    features: ['Left/right icon slots', 'Clear trigger button', 'WCAG AAA focus-ui99 ring', 'Aria-invalid styling'],
    usageSnippet: `import { Input } from "@99/ui"\nimport { Search } from "lucide-react"\n\n<Input icon={<Search />} placeholder="Search components..." />`,
    codeSnippet: `export const Input = React.forwardRef<HTMLInputElement, InputProps>((props, ref) => <input ref={ref} {...props} />);`,
    props: [
      { name: 'label', type: 'string', description: 'Input label text.' },
      { name: 'error', type: 'string', description: 'Error message.' },
    ],
  },
  {
    id: 'textarea',
    name: 'textarea',
    title: 'Textarea',
    description: 'Auto-resizing multi-line text input with character limit countdown and markdown support.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add textarea',
    features: ['Auto-grow height', 'Max length counter', 'Obsidian velvet background'],
    usageSnippet: `import { Textarea } from "@99/ui"\n\n<Textarea placeholder="Write issue description..." rows={4} />`,
    codeSnippet: `export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>((props, ref) => <textarea ref={ref} {...props} />);`,
    props: [{ name: 'rows', type: 'number', description: 'Default visible rows.' }],
  },
  {
    id: 'search-bar',
    name: 'search-bar',
    title: 'Search Bar',
    description: 'Quick-filter search input with search icon, instant clear trigger, and keyboard shortcut badge.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add search-bar',
    features: ['Embedded Kbd shortcut', 'Instant clear button', 'Debounced onChange callback'],
    usageSnippet: `import { SearchBar } from "@99/ui"\n\n<SearchBar value={query} onChange={setQuery} shortcut="⌘K" />`,
    codeSnippet: `export const SearchBar = ({ value, onChange, shortcut }) => <Input value={value} ... />;`,
    props: [{ name: 'shortcut', type: 'string', description: 'Hotkey hint to display.' }],
  },
  {
    id: 'password-input',
    name: 'password-input',
    title: 'Password Input',
    description: 'Secure password field with visibility toggle eye, zxcvbn entropy bar, and criteria checklist.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add password-input',
    features: ['Eye visibility toggle', 'Color-coded strength bar', 'Accessibility aria-live strength announcements'],
    usageSnippet: `import { PasswordInput } from "@99/ui"\n\n<PasswordInput label="Enterprise Password" showStrength />`,
    codeSnippet: `export const PasswordInput = ({ showStrength, ...props }) => { /* implementation */ };`,
    props: [{ name: 'showStrength', type: 'boolean', description: 'Toggles password score meter.' }],
  },
  {
    id: 'number-field',
    name: 'number-field',
    title: 'Number Field',
    description: 'Clamped numeric stepper input with keyboard up/down arrows and holding velocity acceleration.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add number-field',
    features: ['Min/max clamping', 'Step increment buttons', 'Wheel scrolling support'],
    usageSnippet: `import { NumberField } from "@99/ui"\n\n<NumberField min={0} max={100} step={5} defaultValue={25} />`,
    codeSnippet: `export const NumberField = ({ min, max, step, value, onChange }) => { /* ... */ };`,
    props: [{ name: 'step', type: 'number', description: 'Increment/decrement interval.' }],
  },
  {
    id: 'otp-input',
    name: 'otp-input',
    title: 'OTP / Pin Input',
    description: 'Segmented multi-cell one-time passcode input with automatic focus forwarding and clipboard paste.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add otp-input',
    features: ['6-cell auto advance', 'Full string paste handling', 'Backspace backward focus'],
    usageSnippet: `import { OTPInput } from "@99/ui"\n\n<OTPInput length={6} onComplete={(code) => verify(code)} />`,
    codeSnippet: `export const OTPInput = ({ length = 6, onComplete }) => { /* ... */ };`,
    props: [{ name: 'length', type: 'number', description: 'Number of passcode digits.' }],
  },
  {
    id: 'color-picker',
    name: 'color-picker',
    title: 'Color Picker',
    description: 'Interactive RGB/Hex color selector with palette presets and alpha slider.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add color-picker',
    features: ['Hex input syncing', 'Quick brand presets', 'Eyedropper API support'],
    usageSnippet: `import { ColorPicker } from "@99/ui"\n\n<ColorPicker value="#10B981" onChange={setColor} label="Accent" />`,
    codeSnippet: `export const ColorPicker = ({ value, onChange, label }) => { /* ... */ };`,
    props: [{ name: 'value', type: 'string', description: 'Active hex color code.' }],
  },
  {
    id: 'date-picker',
    name: 'date-picker',
    title: 'Date Picker',
    description: 'Calendar date picker popover with monthly grid, today highlight, and disabled date filters.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add date-picker',
    features: ['Month pagination', 'Keyboard arrow navigation', 'ISO date serialization'],
    usageSnippet: `import { DatePicker } from "@99/ui"\n\n<DatePicker value="2026-09-24" onChange={setDate} />`,
    codeSnippet: `export const DatePicker = ({ value, onChange }) => { /* ... */ };`,
    props: [{ name: 'value', type: 'string', description: 'Selected ISO date string.' }],
  },
  {
    id: 'time-picker',
    name: 'time-picker',
    title: 'Time Picker',
    description: 'Filterable listbox time selector with hour/minute scrolls and 12h/24h toggle.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add time-picker',
    features: ['15/30-minute steps', 'Keyboard typeahead', 'Scroll into view on open'],
    usageSnippet: `import { TimePicker } from "@99/ui"\n\n<TimePicker value="09:30" onChange={setTime} />`,
    codeSnippet: `export const TimePicker = ({ value, onChange }) => { /* ... */ };`,
    props: [{ name: 'value', type: 'string', description: 'Selected time HH:mm.' }],
  },
  {
    id: 'combobox',
    name: 'combobox',
    title: 'Combobox',
    description: 'Searchable auto-completing dropdown with custom create-option flow powered by cmdk.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['cmdk', 'lucide-react'],
    cliCommand: 'npx @99/ui add combobox',
    features: ['Fuzzy text filtering', 'Virtual list rendering', 'Create new item option'],
    usageSnippet: `import { Combobox } from "@99/ui"\n\n<Combobox options={[{ label: 'Linear', value: 'linear' }]} value={v} onChange={setV} />`,
    codeSnippet: `export const Combobox = ({ options, value, onChange }) => { /* ... */ };`,
    props: [{ name: 'options', type: 'Array<{ label: string; value: string }>', description: 'Selectable items.' }],
  },
  {
    id: 'dropdown',
    name: 'dropdown',
    title: 'Dropdown Select',
    description: 'Accessible select menu with full ARIA listbox semantics, keyboard typeahead, and icon support.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add dropdown',
    features: ['ARIA 1.2 listbox compliance', 'Keyboard Home/End/Arrows navigation', 'Specular menu highlight'],
    usageSnippet: `import { Dropdown } from "@99/ui"\n\n<Dropdown options={[{ label: 'Active', value: '1' }]} value={val} onChange={setVal} />`,
    codeSnippet: `export const Dropdown = ({ options, value, onChange }) => { /* ... */ };`,
    props: [{ name: 'options', type: 'DropdownOption[]', description: 'List of menu options.' }],
  },
  {
    id: 'slider',
    name: 'slider',
    title: 'Slider',
    description: 'Continuous or stepped value slider with haptic track fill, RTL mirroring, and aria-valuetext.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-slider'],
    cliCommand: 'npx @99/ui add slider',
    features: ['RTL mirror support', 'Touch-friendly 44px thumb hit area', 'Specular rim fill'],
    usageSnippet: `import { Slider } from "@99/ui"\n\n<Slider value={[75]} onValueChange={setVal} max={100} />`,
    codeSnippet: `export const Slider = RadixSlider.Root;`,
    props: [{ name: 'max', type: 'number', description: 'Upper numeric bound.' }],
  },
  {
    id: 'file-upload',
    name: 'file-upload',
    title: 'File Upload & Dropzone',
    description: 'Drag and drop file upload container with file preview cards, progress rings, and file size limits.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add file-upload',
    features: ['Drag over highlight', 'MIME type filtering', 'Multi-file staging list'],
    usageSnippet: `import { FileUpload } from "@99/ui"\n\n<FileUpload onFilesSelected={(files) => upload(files)} maxFiles={5} />`,
    codeSnippet: `export const FileUpload = ({ onFilesSelected, maxFiles }) => { /* ... */ };`,
    props: [{ name: 'maxFiles', type: 'number', description: 'Max allowed concurrent uploads.' }],
  },
  {
    id: 'rich-text-editor-bar',
    name: 'rich-text-editor-bar',
    title: 'Rich Text Toolbar',
    description: 'Obsidian floating formatting toolbar with bold, italic, code, link, and list triggers.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add rich-text-editor-bar',
    features: ['Floating glass bar', 'Active format highlights', 'Keyboard hotkey triggers'],
    usageSnippet: `import { RichTextEditorBar } from "@99/ui"\n\n<RichTextEditorBar onFormat={(fmt) => exec(fmt)} />`,
    codeSnippet: `export const RichTextEditorBar = ({ onFormat }) => <div>...</div>;`,
    props: [{ name: 'onFormat', type: '(format: string) => void', description: 'Formatting event callback.' }],
  },
  {
    id: 'signature-pad',
    name: 'signature-pad',
    title: 'Signature Pad',
    description: 'Smooth vector stylus signature drawing pad with PNG/SVG vector export and clear action.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add signature-pad',
    features: ['Bezier curve smoothing', 'Pressure-sensitive line weight', 'Transparent PNG export'],
    usageSnippet: `import { SignaturePad } from "@99/ui"\n\n<SignaturePad onSave={(dataUrl) => sign(dataUrl)} />`,
    codeSnippet: `export const SignaturePad = ({ onSave }) => <canvas />;`,
    props: [{ name: 'onSave', type: '(dataUrl: string) => void', description: 'Export callback.' }],
  },
  {
    id: 'rating',
    name: 'rating',
    title: 'Rating',
    description: 'Fractional star rating input with keyboard Arrow navigation and half-star hover preview.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add rating',
    features: ['Precision fractional ratings', 'Keyboard Left/Right step navigation', 'Amber glowing active stars'],
    usageSnippet: `import { Rating } from "@99/ui"\n\n<Rating value={4.5} onChange={setRating} precision={0.5} />`,
    codeSnippet: `export const Rating = ({ value, onChange, precision = 1 }) => { /* ... */ };`,
    props: [{ name: 'precision', type: '0.5 | 1', description: 'Step resolution.' }],
  },
  {
    id: 'tag-input',
    name: 'tag-input',
    title: 'Tag Input',
    description: 'Interactive multi-token input with auto-tagging on Enter/Comma, backspace deletion, and autocomplete.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add tag-input',
    features: ['Enter / Comma tokenizing', 'Backspace delete last token', 'Max tags limit counter'],
    usageSnippet: `import { TagInput } from "@99/ui"\n\n<TagInput tags={tags} onChange={setTags} label="Keywords" />`,
    codeSnippet: `export const TagInput = ({ tags, onChange, label }) => { /* ... */ };`,
    props: [{ name: 'tags', type: 'string[]', description: 'Active token array.' }],
  },
  {
    id: 'label',
    name: 'label',
    title: 'Label',
    description: 'Accessible form control label with required indicator asterisk and disabled state synchronization.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-label'],
    cliCommand: 'npx @99/ui add label',
    features: ['Radix Label primitive', 'Required indicator', 'Peer focus highlight'],
    usageSnippet: `import { Label } from "@99/ui"\n\n<Label htmlFor="email" required>Work Email</Label>`,
    codeSnippet: `export const Label = RadixLabel.Root;`,
    props: [{ name: 'required', type: 'boolean', description: 'Appends red asterisk.' }],
  },
  {
    id: 'form-field',
    name: 'form-field',
    title: 'Form Field',
    description: 'Complete form row container assembling Label, Input, Hint text, and Error message with ARIA linking.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add form-field',
    features: ['Automatic aria-describedby', 'Error state animation', 'Flexible child control slot'],
    usageSnippet: `import { FormField, Input } from "@99/ui"\n\n<FormField label="Username" hint="Unique handle" error={err}><Input /></FormField>`,
    codeSnippet: `export const FormField = ({ label, hint, error, children }) => <div>...</div>;`,
    props: [{ name: 'hint', type: 'string', description: 'Helpful guidance text.' }],
  },
  {
    id: 'field-error',
    name: 'field-error',
    title: 'Field Error',
    description: 'Accessible validation error message with alert circle icon and rose color tinting.',
    category: 'Forms',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add field-error',
    features: ['Role alert semantic', 'Rose icon & text', 'Smooth enter transition'],
    usageSnippet: `import { FieldError } from "@99/ui"\n\n<FieldError message="Invalid email address" />`,
    codeSnippet: `export const FieldError = ({ message }) => <span>{message}</span>;`,
    props: [{ name: 'message', type: 'string', description: 'Error notification text.' }],
  },

  // ──────────────────────────────
  // 3. SELECTION & SWITCHES (6 Elements)
  // ──────────────────────────────
  {
    id: 'switch',
    name: 'switch',
    title: 'Switch',
    description: 'A tactile toggle switch with haptic spring physics, specular track rim, and RTL mirroring.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-switch'],
    cliCommand: 'npx @99/ui add switch',
    features: ['Spring thumb movement', 'WCAG 2.2 touch target ≥44px', 'Full RTL direction support'],
    usageSnippet: `import { Switch } from "@99/ui"\n\n<Switch checked={enabled} onCheckedChange={setEnabled} />`,
    codeSnippet: `export const Switch = RadixSwitch.Root;`,
    props: [{ name: 'checked', type: 'boolean', description: 'Active toggle state.' }],
  },
  {
    id: 'checkbox',
    name: 'checkbox',
    title: 'Checkbox',
    description: 'Accessible check control with animated SVG checkmark, indeterminate minus state, and specular border.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-checkbox'],
    cliCommand: 'npx @99/ui add checkbox',
    features: ['Indeterminate state support', 'Emerald active check', 'Keyboard Space toggle'],
    usageSnippet: `import { Checkbox } from "@99/ui"\n\n<Checkbox id="terms" label="Accept terms" checked={checked} onCheckedChange={setChecked} />`,
    codeSnippet: `export const Checkbox = RadixCheckbox.Root;`,
    props: [{ name: 'checked', type: "boolean | 'indeterminate'", description: 'Check status.' }],
  },
  {
    id: 'radio-group',
    name: 'radio-group',
    title: 'Radio Group',
    description: 'A set of checkable buttons—known as radio buttons—where no more than one can be checked at once.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-radio-group'],
    cliCommand: 'npx @99/ui add radio-group',
    features: ['Roving tabindex keyboard focus', 'Specular active dot indicator', 'Vertical and horizontal layout'],
    usageSnippet: `import { RadioGroup, RadioGroupItem } from "@99/ui"\n\n<RadioGroup defaultValue="1"><RadioGroupItem value="1" label="Standard" /></RadioGroup>`,
    codeSnippet: `export const RadioGroup = RadixRadioGroup.Root;`,
    props: [{ name: 'defaultValue', type: 'string', description: 'Default active value.' }],
  },
  {
    id: 'segmented-control',
    name: 'segmented-control',
    title: 'Segmented Control',
    description: 'Apple HIG-inspired liquid glass segmented pill switcher with fluid spring physics indicator.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['motion'],
    cliCommand: 'npx @99/ui add segmented-control',
    features: ['LayoutId spring indicator', 'Roving tabindex arrow navigation', 'Liquid glass base styling'],
    usageSnippet: `import { SegmentedControl } from "@99/ui"\n\n<SegmentedControl options={[{ label: 'Day', value: 'day' }]} value={tab} onChange={setTab} />`,
    codeSnippet: `export const SegmentedControl = ({ options, value, onChange }) => { /* ... */ };`,
    props: [{ name: 'options', type: 'SegmentOption[]', description: 'Available tabs list.' }],
  },
  {
    id: 'aspect-ratio',
    name: 'aspect-ratio',
    title: 'Aspect Ratio',
    description: 'Maintains uniform aspect ratio for images, video players, and responsive media cards.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-aspect-ratio'],
    cliCommand: 'npx @99/ui add aspect-ratio',
    features: ['16:9, 4:3, 1:1, 21:9 support', 'Zero layout shift', 'Radix primitive'],
    usageSnippet: `import { AspectRatio } from "@99/ui"\n\n<AspectRatio ratio={16 / 9}><img src="/hero.jpg" /></AspectRatio>`,
    codeSnippet: `export const AspectRatio = RadixAspectRatio.Root;`,
    props: [{ name: 'ratio', type: 'number', default: '16 / 9', description: 'Width-to-height ratio.' }],
  },
  {
    id: 'collapsible',
    name: 'collapsible',
    title: 'Collapsible',
    description: 'An interactive component which expands/collapses a panel with smooth height transitions.',
    category: 'Selection',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-collapsible'],
    cliCommand: 'npx @99/ui add collapsible',
    features: ['Smooth height animation', 'Accessible aria-expanded', 'Radix disclosure primitive'],
    usageSnippet: `import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@99/ui"\n\n<Collapsible><CollapsibleTrigger>Toggle</CollapsibleTrigger><CollapsibleContent>Details</CollapsibleContent></Collapsible>`,
    codeSnippet: `export const Collapsible = RadixCollapsible.Root;`,
    props: [{ name: 'open', type: 'boolean', description: 'Controlled open state.' }],
  },

  // ──────────────────────────────
  // 4. DATA DISPLAY & VISUALIZERS (20 Elements)
  // ──────────────────────────────
  {
    id: 'badge',
    name: 'badge',
    title: 'Badge & Status',
    description: 'Semantic status indicators, Linear issue priorities, and metadata tag capsules.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add badge',
    features: ['IssueStatus: todo, in_progress, done', 'PriorityLevel: urgent, high, medium, low', 'WCAG AAA contrast'],
    usageSnippet: `import { StatusBadge, PriorityBadge } from "@99/ui"\n\n<StatusBadge status="in_progress" />\n<PriorityBadge priority="urgent" />`,
    codeSnippet: `export const StatusBadge = ({ status }) => <span>{status}</span>;`,
    props: [{ name: 'status', type: "'todo' | 'in_progress' | 'done'", description: 'Lifecycle status.' }],
  },
  {
    id: 'stat-tile',
    name: 'stat-tile',
    title: 'Stat Tile',
    description: 'Executive metric card displaying large numeric figures with trend direction, subtitle, and badge.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add stat-tile',
    features: ['Monospaced primary numbers', 'Positive/negative delta pill', 'Obsidian glass card background'],
    usageSnippet: `import { StatTile } from "@99/ui"\n\n<StatTile title="Total Invocations" value="1.4M" change="+18.4%" trend="up" />`,
    codeSnippet: `export const StatTile = ({ title, value, change, trend }) => <div>...</div>;`,
    props: [{ name: 'value', type: 'string', description: 'Primary numeric metric.' }],
  },
  {
    id: 'trend-delta',
    name: 'trend-delta',
    title: 'Trend Delta',
    description: 'Compact positive/negative metric variance pill with arrow indicator.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add trend-delta',
    features: ['Emerald positive green', 'Rose negative red', 'Neutral flat zero'],
    usageSnippet: `import { TrendDelta } from "@99/ui"\n\n<TrendDelta value="+24.8%" trend="up" />`,
    codeSnippet: `export const TrendDelta = ({ value, trend }) => <span>{value}</span>;`,
    props: [{ name: 'trend', type: "'up' | 'down' | 'neutral'", description: 'Trend vector.' }],
  },
  {
    id: 'sparkline',
    name: 'sparkline',
    title: 'Sparkline',
    description: 'Ultra-lightweight zero-dependency SVG micro sparkline chart for inline trends.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add sparkline',
    features: ['Pure SVG vector path', 'Gradient fill area', 'Zero external graphing bundle weight'],
    usageSnippet: `import { Sparkline } from "@99/ui"\n\n<Sparkline data={[10, 25, 18, 42, 38, 55]} color="#10B981" />`,
    codeSnippet: `export const Sparkline = ({ data, color = '#10B981' }) => <svg>...</svg>;`,
    props: [{ name: 'data', type: 'number[]', description: 'Array of datapoints.' }],
  },
  {
    id: 'donut-ring',
    name: 'donut-ring',
    title: 'Donut Ring',
    description: 'Radial progress donut chart with stroke-dashoffset animation and center label.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add donut-ring',
    features: ['Smooth radial animation', 'Center metric label slot', 'Specular rim glow'],
    usageSnippet: `import { DonutRing } from "@99/ui"\n\n<DonutRing percentage={78} label="78%" color="#10B981" />`,
    codeSnippet: `export const DonutRing = ({ percentage, label, color }) => <svg>...</svg>;`,
    props: [{ name: 'percentage', type: 'number', description: 'Progress percentage (0-100).' }],
  },
  {
    id: 'heat-map-calendar',
    name: 'heat-map-calendar',
    title: 'HeatMap Calendar',
    description: 'GitHub-style activity contribution matrix grid with intensity tooltips.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add heat-map-calendar',
    features: ['5 chromatic intensity levels', 'Tooltip date count', 'Responsive overflow scroll'],
    usageSnippet: `import { HeatMapCalendar } from "@99/ui"\n\n<HeatMapCalendar data={activityData} />`,
    codeSnippet: `export const HeatMapCalendar = ({ data }) => <div>...</div>;`,
    props: [{ name: 'data', type: 'Array<{ date: string; count: number }>', description: 'Daily activity.' }],
  },
  {
    id: 'meter-bar',
    name: 'meter-bar',
    title: 'Meter Bar',
    description: 'Multi-segment threshold meter displaying resource allocations and storage limits.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add meter-bar',
    features: ['Multi-color segments', 'Legend breakdown', 'Specular bar border'],
    usageSnippet: `import { MeterBar } from "@99/ui"\n\n<MeterBar segments={[{ label: 'Code', value: 45, color: '#3B82F6' }]} />`,
    codeSnippet: `export const MeterBar = ({ segments }) => <div>...</div>;`,
    props: [{ name: 'segments', type: 'Array<{ label: string; value: number; color: string }>', description: 'Meter breakdown.' }],
  },
  {
    id: 'progress',
    name: 'progress',
    title: 'Progress Bar',
    description: 'Horizontal linear progress bar with animated shimmer indicator and indeterminate pulse.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-progress'],
    cliCommand: 'npx @99/ui add progress',
    features: ['Indeterminate pulse animation', 'Radix primitive', 'Specular rim fill'],
    usageSnippet: `import { Progress } from "@99/ui"\n\n<Progress value={65} />`,
    codeSnippet: `export const Progress = RadixProgress.Root;`,
    props: [{ name: 'value', type: 'number', description: 'Percentage progress.' }],
  },
  {
    id: 'skeleton',
    name: 'skeleton',
    title: 'Skeleton',
    description: 'Content loading placeholder with subtle velvet shimmer animation preventing cumulative layout shift.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add skeleton',
    features: ['Linear gradient shimmer loop', 'Configurable radius and dimension', 'Zero CLS'],
    usageSnippet: `import { Skeleton } from "@99/ui"\n\n<Skeleton className="w-48 h-4 rounded-xl" />`,
    codeSnippet: `export const Skeleton = ({ className }) => <div className={\`animate-pulse bg-zinc-800 \${className}\`} />;`,
    props: [{ name: 'className', type: 'string', description: 'Tailwind styling.' }],
  },
  {
    id: 'table',
    name: 'table',
    title: 'Data Table',
    description: 'Enterprise data table with sticky header, zebra striping, row hover highlights, and sorting.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add table',
    features: ['Zebra striping option', 'Hoverable interactive rows', 'Specular table border'],
    usageSnippet: `import { Table, TableHeader, TableRow, TableCell } from "@99/ui"\n\n<Table><TableHeader><TableRow>...</TableRow></TableHeader></Table>`,
    codeSnippet: `export const Table = ({ children }) => <table>{children}</table>;`,
    props: [{ name: 'children', type: 'ReactNode', description: 'Table rows and cells.' }],
  },
  {
    id: 'pagination',
    name: 'pagination',
    title: 'Pagination',
    description: 'Accessible page navigation with previous/next buttons, page number list, and ellipsis truncation.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add pagination',
    features: ['Smart ellipsis truncation', 'Keyboard tab navigation', 'Aria-current page indicator'],
    usageSnippet: `import { Pagination } from "@99/ui"\n\n<Pagination currentPage={2} totalPages={10} onPageChange={setPage} />`,
    codeSnippet: `export const Pagination = ({ currentPage, totalPages, onPageChange }) => { /* ... */ };`,
    props: [{ name: 'totalPages', type: 'number', description: 'Total available pages.' }],
  },
  {
    id: 'tree-view',
    name: 'tree-view',
    title: 'Tree View',
    description: 'Hierarchical file and folder explorer with collapsible branches, node icons, and selection focus.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add tree-view',
    features: ['Recursive folder collapse', 'File extension icon mapping', 'Keyboard Arrow navigation'],
    usageSnippet: `import { TreeView } from "@99/ui"\n\n<TreeView data={treeData} onSelectNode={handleSelect} />`,
    codeSnippet: `export const TreeView = ({ data, onSelectNode }) => { /* ... */ };`,
    props: [{ name: 'data', type: 'TreeNode[]', description: 'Hierarchical nodes.' }],
  },
  {
    id: 'timeline',
    name: 'timeline',
    title: 'Timeline',
    description: 'Vertical chronological event feed with icon nodes, connecting hairlines, and status timestamps.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add timeline',
    features: ['Connecting timeline hairline', 'Node color badges', 'Responsive mobile layout'],
    usageSnippet: `import { Timeline } from "@99/ui"\n\n<Timeline events={[{ title: 'Released v1.0', time: 'Today' }]} />`,
    codeSnippet: `export const Timeline = ({ events }) => <div>...</div>;`,
    props: [{ name: 'events', type: 'TimelineEvent[]', description: 'List of events.' }],
  },
  {
    id: 'stepper',
    name: 'stepper',
    title: 'Stepper',
    description: 'Multi-step workflow progress indicator with active step highlighting and completion checks.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add stepper',
    features: ['Active step spring animation', 'Checkmark completed state', 'Horizontal/Vertical mode'],
    usageSnippet: `import { Stepper } from "@99/ui"\n\n<Stepper steps={['Account', 'Profile', 'Billing']} activeStep={1} />`,
    codeSnippet: `export const Stepper = ({ steps, activeStep }) => <div>...</div>;`,
    props: [{ name: 'activeStep', type: 'number', description: 'Current active index.' }],
  },
  {
    id: 'code-block',
    name: 'code-block',
    title: 'Code Block',
    description: 'Syntax-highlighted code container with language badge, line numbers, and copy button.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add code-block',
    features: ['Line numbering', 'Language badge tag', 'One-click copy to clipboard'],
    usageSnippet: `import { CodeBlock } from "@99/ui"\n\n<CodeBlock code="const a = 1;" language="tsx" filename="App.tsx" />`,
    codeSnippet: `export const CodeBlock = ({ code, language, filename }) => <div>...</div>;`,
    props: [{ name: 'code', type: 'string', description: 'Code string content.' }],
  },
  {
    id: 'carousel',
    name: 'carousel',
    title: 'Carousel',
    description: 'Touch-swipeable content carousel with scroll snap, previous/next controls, and dot indicators.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add carousel',
    features: ['CSS scroll-snap zero dependency', 'Touch drag support', 'Page dot indicators'],
    usageSnippet: `import { Carousel } from "@99/ui"\n\n<Carousel items={[<Card key="1" />, <Card key="2" />]} />`,
    codeSnippet: `export const Carousel = ({ items }) => <div>...</div>;`,
    props: [{ name: 'items', type: 'ReactNode[]', description: 'Slide elements.' }],
  },
  {
    id: 'diff-viewer',
    name: 'diff-viewer',
    title: 'Diff Viewer',
    description: 'Git-style split and unified diff viewer displaying additions, deletions, and line changes.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add diff-viewer',
    features: ['Unified line diffs', 'Green addition / Red deletion tints', 'Monospaced font'],
    usageSnippet: `import { DiffViewer } from "@99/ui"\n\n<DiffViewer fileName="config.ts" lines={diffLines} />`,
    codeSnippet: `export const DiffViewer = ({ fileName, lines }) => <div>...</div>;`,
    props: [{ name: 'lines', type: 'DiffLine[]', description: 'Diff lines array.' }],
  },
  {
    id: 'kanban-board',
    name: 'kanban-board',
    title: 'Kanban Board',
    description: 'Multi-column workflow board with interactive cards, assignees, priorities, and column counters.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add kanban-board',
    features: ['Multi-column board', 'Card status moves', 'Linear-grade tags and avatars'],
    usageSnippet: `import { KanbanBoard } from "@99/ui"\n\n<KanbanBoard />`,
    codeSnippet: `export const KanbanBoard = () => <div>...</div>;`,
    props: [],
  },
  {
    id: 'calendar-view',
    name: 'calendar-view',
    title: 'Calendar View',
    description: 'Full-month calendar grid with scheduled event markers, today indicator, and month pagination.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add calendar-view',
    features: ['Event tag chips', 'Month pagination', 'Obsidian glass styling'],
    usageSnippet: `import { CalendarView } from "@99/ui"\n\n<CalendarView events={eventsList} />`,
    codeSnippet: `export const CalendarView = ({ events }) => <div>...</div>;`,
    props: [{ name: 'events', type: 'CalendarEvent[]', description: 'Scheduled events.' }],
  },
  {
    id: 'audio-player',
    name: 'audio-player',
    title: 'Audio Player',
    description: 'Velvet acoustic audio waveform player with play/pause spring button, scrubber, and time indicator.',
    category: 'Data Display',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add audio-player',
    features: ['Waveform visualizer bars', 'Interactive time scrubber', 'Play/pause spring toggle'],
    usageSnippet: `import { AudioPlayer } from "@99/ui"\n\n<AudioPlayer title="Obsidian Velvet" artist="99 Lab" durationSec={180} />`,
    codeSnippet: `export const AudioPlayer = ({ title, artist, durationSec }) => <div>...</div>;`,
    props: [{ name: 'durationSec', type: 'number', description: 'Track duration in seconds.' }],
  },

  // ──────────────────────────────
  // 5. OVERLAYS, MENUS & DIALOGS (18 Elements)
  // ──────────────────────────────
  {
    id: 'dialog',
    name: 'dialog',
    title: 'Dialog',
    description: 'Accessible modal dialog with backdrop blur, focus trap, and Escape key dismissal.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-dialog', 'lucide-react'],
    cliCommand: 'npx @99/ui add dialog',
    features: ['Backdrop blur scrim', 'Automatic focus trap and restoration', 'Specular modal rim highlight'],
    usageSnippet: `import { Dialog, DialogTrigger, DialogContent } from "@99/ui"\n\n<Dialog><DialogTrigger>Open</DialogTrigger><DialogContent>Content</DialogContent></Dialog>`,
    codeSnippet: `export const Dialog = RadixDialog.Root;`,
    props: [{ name: 'open', type: 'boolean', description: 'Controlled modal state.' }],
  },
  {
    id: 'alert-dialog',
    name: 'alert-dialog',
    title: 'Alert Dialog',
    description: 'A modal dialog that interrupts the user with critical information and requires an explicit response.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-alert-dialog'],
    cliCommand: 'npx @99/ui add alert-dialog',
    features: ['Destructive action confirmation', 'Aria-alertdialog semantics', 'Radix primitive'],
    usageSnippet: `import { AlertDialog, AlertDialogTrigger, AlertDialogContent } from "@99/ui"\n\n<AlertDialog><AlertDialogTrigger>Delete</AlertDialogTrigger><AlertDialogContent>Are you sure?</AlertDialogContent></AlertDialog>`,
    codeSnippet: `export const AlertDialog = RadixAlertDialog.Root;`,
    props: [],
  },
  {
    id: 'sheet',
    name: 'sheet',
    title: 'Sheet / Drawer',
    description: 'Slide-over drawer extending from screen edges (right, left, top, bottom) with smooth physics.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-dialog', 'lucide-react'],
    cliCommand: 'npx @99/ui add sheet',
    features: ['4 side directions (right, left, top, bottom)', 'Spring slide motion', 'Scrollable body container'],
    usageSnippet: `import { Sheet, SheetTrigger, SheetContent } from "@99/ui"\n\n<Sheet><SheetTrigger>Edit</SheetTrigger><SheetContent side="right">Form</SheetContent></Sheet>`,
    codeSnippet: `export const Sheet = RadixDialog.Root;`,
    props: [{ name: 'side', type: "'right' | 'left' | 'top' | 'bottom'", default: "'right'", description: 'Slide direction.' }],
  },
  {
    id: 'popover',
    name: 'popover',
    title: 'Popover',
    description: 'Floating content container anchored to a trigger element with collision detection.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-popover'],
    cliCommand: 'npx @99/ui add popover',
    features: ['Collision detection positioning', 'Specular glass border', 'Outside click dismissal'],
    usageSnippet: `import { Popover, PopoverTrigger, PopoverContent } from "@99/ui"\n\n<Popover><PopoverTrigger>Open</PopoverTrigger><PopoverContent>Content</PopoverContent></Popover>`,
    codeSnippet: `export const Popover = RadixPopover.Root;`,
    props: [{ name: 'align', type: "'start' | 'center' | 'end'", default: "'center'", description: 'Anchor alignment.' }],
  },
  {
    id: 'dropdown-menu',
    name: 'dropdown-menu',
    title: 'Dropdown Menu',
    description: 'Cascading action menu with submenus, checkboxes, radio items, shortcuts, and separators.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-dropdown-menu', 'lucide-react'],
    cliCommand: 'npx @99/ui add dropdown-menu',
    features: ['Nested submenus', 'Keyboard Arrow navigation', 'Shortcut key badges'],
    usageSnippet: `import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@99/ui"\n\n<DropdownMenu><DropdownMenuTrigger>Actions</DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>Edit</DropdownMenuItem></DropdownMenuContent></DropdownMenu>`,
    codeSnippet: `export const DropdownMenu = RadixDropdownMenu.Root;`,
    props: [],
  },
  {
    id: 'tooltip',
    name: 'tooltip',
    title: 'Tooltip',
    description: 'Accessible floating label that appears on hover or keyboard focus with delay calibration.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-tooltip'],
    cliCommand: 'npx @99/ui add tooltip',
    features: ['Zero layout shift', 'Keyboard focus trigger', 'Radix Tooltip primitive'],
    usageSnippet: `import { Tooltip } from "@99/ui"\n\n<Tooltip content="Quick actions (⌘K)"><Button>Search</Button></Tooltip>`,
    codeSnippet: `export const Tooltip = ({ content, children }) => <div>{children}</div>;`,
    props: [{ name: 'content', type: 'ReactNode', description: 'Tooltip message.' }],
  },
  {
    id: 'hover-card',
    name: 'hover-card',
    title: 'Hover Card',
    description: 'Rich preview card triggered by sight and hover to preview linked profiles, tickets, and docs.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-hover-card'],
    cliCommand: 'npx @99/ui add hover-card',
    features: ['Grace area mouse hover', 'Radix primitive', 'Obsidian glass styling'],
    usageSnippet: `import { HoverCard, HoverCardTrigger, HoverCardContent } from "@99/ui"\n\n<HoverCard><HoverCardTrigger>@linear</HoverCardTrigger><HoverCardContent>Profile</HoverCardContent></HoverCard>`,
    codeSnippet: `export const HoverCard = RadixHoverCard.Root;`,
    props: [],
  },
  {
    id: 'menubar',
    name: 'menubar',
    title: 'Menubar',
    description: 'Desktop-grade persistent application menu bar with submenus and keyboard navigation.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-menubar'],
    cliCommand: 'npx @99/ui add menubar',
    features: ['File / Edit / View menus', 'Submenu hierarchies', 'Radix Menubar primitive'],
    usageSnippet: `import { Menubar, MenubarMenu, MenubarTrigger, MenubarContent } from "@99/ui"\n\n<Menubar><MenubarMenu><MenubarTrigger>File</MenubarTrigger><MenubarContent>...</MenubarContent></MenubarMenu></Menubar>`,
    codeSnippet: `export const Menubar = RadixMenubar.Root;`,
    props: [],
  },
  {
    id: 'navigation-menu',
    name: 'navigation-menu',
    title: 'Navigation Menu',
    description: 'Top-level header navigation system with responsive flyout panels and smooth indicator transitions.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-navigation-menu'],
    cliCommand: 'npx @99/ui add navigation-menu',
    features: ['Rich multi-column flyouts', 'Animated indicator chevron', 'Radix primitive'],
    usageSnippet: `import { NavigationMenu, NavigationMenuList, NavigationMenuItem } from "@99/ui"\n\n<NavigationMenu><NavigationMenuList>...</NavigationMenuList></NavigationMenu>`,
    codeSnippet: `export const NavigationMenu = RadixNavigationMenu.Root;`,
    props: [],
  },
  {
    id: 'command',
    name: 'command',
    title: 'Command Menu (cmdk)',
    description: 'Fast, composable command palette spotlight dialog powered by cmdk.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['cmdk', 'lucide-react'],
    cliCommand: 'npx @99/ui add command',
    features: ['Fuzzy score search', 'Grouped command items', 'Shortcut key mapping'],
    usageSnippet: `import { Command, CommandInput, CommandList, CommandItem } from "@99/ui"\n\n<Command><CommandInput placeholder="Type a command..." /><CommandList><CommandItem>New Tab</CommandItem></CommandList></Command>`,
    codeSnippet: `export const Command = cmdk.Command;`,
    props: [],
  },
  {
    id: 'command-bar',
    name: 'command-bar',
    title: 'Command Bar',
    description: 'Linear-grade sticky command palette modal with quick actions and filter search.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['cmdk', 'lucide-react'],
    cliCommand: 'npx @99/ui add command-bar',
    features: ['Global ⌘K activation', 'Recent searches history', 'Smooth spring enter'],
    usageSnippet: `import { CommandBar } from "@99/ui"\n\n<CommandBar isOpen={open} onClose={() => setOpen(false)} />`,
    codeSnippet: `export const CommandBar = ({ isOpen, onClose }) => { /* ... */ };`,
    props: [{ name: 'isOpen', type: 'boolean', description: 'Visibility state.' }],
  },
  {
    id: 'keyboard-shortcuts-dialog',
    name: 'keyboard-shortcuts-dialog',
    title: 'Shortcuts Dialog',
    description: 'Comprehensive keyboard shortcuts cheatsheet modal grouped by workflow category.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add keyboard-shortcuts-dialog',
    features: ['Grouped hotkey list', 'Searchable shortcut filters', 'Kbd visual styling'],
    usageSnippet: `import { KeyboardShortcutsDialog } from "@99/ui"\n\n<KeyboardShortcutsDialog isOpen={showHelp} onClose={() => setShowHelp(false)} />`,
    codeSnippet: `export const KeyboardShortcutsDialog = ({ isOpen, onClose }) => <div>...</div>;`,
    props: [{ name: 'isOpen', type: 'boolean', description: 'Dialog open state.' }],
  },
  {
    id: 'tour-guide',
    name: 'tour-guide',
    title: 'Tour Guide & Beacon',
    description: 'Interactive step-by-step onboarding walkthrough with pulsing beacons and spotlights.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add tour-guide',
    features: ['Pulsing highlight beacon', 'Step counter navigation', 'Target element anchoring'],
    usageSnippet: `import { TourGuide } from "@99/ui"\n\n<TourGuide steps={tourSteps} onComplete={() => done()} />`,
    codeSnippet: `export const TourGuide = ({ steps, onComplete }) => <div>...</div>;`,
    props: [{ name: 'steps', type: 'TourStep[]', description: 'Walkthrough step sequence.' }],
  },
  {
    id: 'confetti',
    name: 'confetti',
    title: 'Confetti Celebration',
    description: 'High-performance canvas particle burst celebrating project milestone achievements.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add confetti',
    features: ['Physics particle physics', 'Custom brand palette colors', 'Zero CPU drag after finish'],
    usageSnippet: `import { Confetti } from "@99/ui"\n\n<Confetti trigger={isCompleted} />`,
    codeSnippet: `export const Confetti = ({ trigger }) => <canvas />;`,
    props: [{ name: 'trigger', type: 'boolean', description: 'Fires confetti burst on true.' }],
  },
  {
    id: 'toast',
    name: 'toast',
    title: 'Toast & Notification',
    description: 'Animated bottom-corner status notifications with pause-on-hover and auto-dismissal.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react', 'motion'],
    cliCommand: 'npx @99/ui add toast',
    features: ['Pause on mouse hover', 'Escape key dismissal', 'Maximum concurrent stack limit'],
    usageSnippet: `import { useApp } from "@/core/context/AppContext"\n\nconst { addToast } = useApp();\naddToast("Changes saved successfully", "success");`,
    codeSnippet: `export const Toast = ({ message, type, onClose }) => <div>...</div>;`,
    props: [{ name: 'type', type: "'success' | 'error' | 'info'", description: 'Toast severity.' }],
  },
  {
    id: 'banner',
    name: 'banner',
    title: 'Announcement Banner',
    description: 'Full-width top announcement banner with dismiss button and action link.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add banner',
    features: ['Persistent dismiss state', 'Action link button', 'Specular rim outline'],
    usageSnippet: `import { Banner } from "@99/ui"\n\n<Banner title="UI 99 v2.0 is live" actionLabel="Read changelog" />`,
    codeSnippet: `export const Banner = ({ title, actionLabel, onAction }) => <div>...</div>;`,
    props: [{ name: 'title', type: 'string', description: 'Banner announcement text.' }],
  },
  {
    id: 'alert',
    name: 'alert',
    title: 'Alert',
    description: 'Displays a callout for user attention with semantic icon and colored tint border.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add alert',
    features: ['4 status variants (info, success, warning, destructive)', 'WCAG 2.2 AA contrast', 'Icon slot'],
    usageSnippet: `import { Alert, AlertTitle, AlertDescription } from "@99/ui"\n\n<Alert variant="destructive"><AlertTitle>Error</AlertTitle><AlertDescription>Failed to sync</AlertDescription></Alert>`,
    codeSnippet: `export const Alert = ({ variant, children }) => <div>{children}</div>;`,
    props: [{ name: 'variant', type: "'default' | 'destructive' | 'success' | 'warning'", description: 'Alert tone.' }],
  },
  {
    id: 'empty-placeholder',
    name: 'empty-placeholder',
    title: 'Empty State Placeholder',
    description: 'Zero-data fallback container with icon illustration, helpful guidance, and primary CTA.',
    category: 'Overlays',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add empty-placeholder',
    features: ['Dashed specular border', 'Action button integration', 'Icon slot'],
    usageSnippet: `import { EmptyPlaceholder } from "@99/ui"\n\n<EmptyPlaceholder title="No issues found" description="Create a new task to get started." />`,
    codeSnippet: `export const EmptyPlaceholder = ({ title, description, action }) => <div>...</div>;`,
    props: [{ name: 'title', type: 'string', description: 'Heading for empty state.' }],
  },

  // ──────────────────────────────
  // 6. LAYOUT, NAVIGATION & COMPOSITES (25 Elements)
  // ──────────────────────────────
  {
    id: 'card',
    name: 'card',
    title: 'Card & Surface',
    description: 'Obsidian Dark Velvet container with hairline border and sub-pixel specular rim highlight.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add card',
    features: ['7 visual variants', '7 radius nesting tiers', 'Sub-pixel specular top highlight', 'Deep diffused ambient shadow'],
    usageSnippet: `import { Card, CardHeader, CardTitle, CardContent } from "@99/ui"\n\n<Card><CardHeader><CardTitle>Project Details</CardTitle></CardHeader><CardContent>Content</CardContent></Card>`,
    codeSnippet: `export const Card = ({ children, className }) => <div className={\`bg-[#0B0C11] rounded-3xl \${className}\`}>{children}</div>;`,
    props: [{ name: 'variant', type: "'surface' | 'glass' | 'elevated' | 'sunken'", default: "'surface'", description: 'Background surface layer.' }],
  },
  {
    id: 'separator',
    name: 'separator',
    title: 'Separator',
    description: 'Visually or semantically separates content with hairline divider and optional centered text.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-separator'],
    cliCommand: 'npx @99/ui add separator',
    features: ['Horizontal and vertical orientation', 'Decorative or semantic role', 'Radix primitive'],
    usageSnippet: `import { Separator } from "@99/ui"\n\n<Separator orientation="horizontal" />`,
    codeSnippet: `export const Separator = RadixSeparator.Root;`,
    props: [{ name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'", description: 'Separator axis.' }],
  },
  {
    id: 'scroll-area',
    name: 'scroll-area',
    title: 'Scroll Area',
    description: 'Custom obsidian scrollbar container with smooth hover thumb visibility.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-scroll-area'],
    cliCommand: 'npx @99/ui add scroll-area',
    features: ['Non-intrusive velvet scrollbars', 'Horizontal & Vertical axes', 'Radix primitive'],
    usageSnippet: `import { ScrollArea } from "@99/ui"\n\n<ScrollArea className="h-64">{longList}</ScrollArea>`,
    codeSnippet: `export const ScrollArea = RadixScrollArea.Root;`,
    props: [],
  },
  {
    id: 'sidebar',
    name: 'sidebar',
    title: 'Sidebar Navigation',
    description: 'Responsive desktop/mobile application navigation sidebar with active indicator and badge counters.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add sidebar',
    features: ['Collapsible state support', 'Active cushion pill indicator', 'Section header grouping'],
    usageSnippet: `import { Sidebar } from "@99/ui"\n\n<Sidebar navItems={items} activeId="docs" onNavigate={handleNav} />`,
    codeSnippet: `export const Sidebar = ({ navItems, activeId, onNavigate }) => <aside>...</aside>;`,
    props: [{ name: 'activeId', type: 'string', description: 'Currently active route.' }],
  },
  {
    id: 'tabs',
    name: 'tabs',
    title: 'Tabs',
    description: 'A set of layered sections of content—known as tab panels—that are displayed one at a time.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-tabs'],
    cliCommand: 'npx @99/ui add tabs',
    features: ['Roving tabindex keyboard navigation', 'Specular tab cushion', 'Radix primitive'],
    usageSnippet: `import { Tabs, TabsList, TabsTrigger, TabsContent } from "@99/ui"\n\n<Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger></TabsList><TabsContent value="overview">Details</TabsContent></Tabs>`,
    codeSnippet: `export const Tabs = RadixTabs.Root;`,
    props: [{ name: 'defaultValue', type: 'string', description: 'Initial active tab.' }],
  },
  {
    id: 'accordion',
    name: 'accordion',
    title: 'Accordion',
    description: 'Vertically stacked set of interactive headings that each reveal a section of content.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['@radix-ui/react-accordion', 'lucide-react'],
    cliCommand: 'npx @99/ui add accordion',
    features: ['Single or multiple accordion expansion', 'Smooth height spring animation', 'Chevron rotation indicator'],
    usageSnippet: `import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@99/ui"\n\n<Accordion type="single" collapsible><AccordionItem value="1"><AccordionTrigger>What is UI 99?</AccordionTrigger><AccordionContent>Obsidian Dark velvet design system.</AccordionContent></AccordionItem></Accordion>`,
    codeSnippet: `export const Accordion = RadixAccordion.Root;`,
    props: [{ name: 'type', type: "'single' | 'multiple'", default: "'single'", description: 'Expansion behavior.' }],
  },
  {
    id: 'breadcrumb',
    name: 'breadcrumb',
    title: 'Breadcrumb',
    description: 'Hierarchical navigation trail indicating current position in application tree.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add breadcrumb',
    features: ['Custom chevron / slash separators', 'ARIA breadcrumb semantics', 'Truncated path overflow'],
    usageSnippet: `import { Breadcrumb } from "@99/ui"\n\n<Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Docs' }]} />`,
    codeSnippet: `export const Breadcrumb = ({ items }) => <nav>...</nav>;`,
    props: [{ name: 'items', type: 'BreadcrumbItem[]', description: 'Breadcrumb step items.' }],
  },
  {
    id: 'bottom-navigation',
    name: 'bottom-navigation',
    title: 'Bottom Navigation Dock',
    description: 'Mobile-first liquid glass dock anchored to viewport bottom with velvet active cushions.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react', 'motion'],
    cliCommand: 'npx @99/ui add bottom-navigation',
    features: ['Liquid glass backdrop blur', 'Active cushion indicator', '44px touch target compliance'],
    usageSnippet: `import { BottomNavigation } from "@99/ui"\n\n<BottomNavigation items={dockItems} activeId="home" onSelect={setTab} />`,
    codeSnippet: `export const BottomNavigation = ({ items, activeId, onSelect }) => <nav>...</nav>;`,
    props: [{ name: 'activeId', type: 'string', description: 'Active tab key.' }],
  },
  {
    id: 'top-header',
    name: 'top-header',
    title: 'Top Header Bar',
    description: 'Sticky minimalist header with brand logo, search launcher, theme switcher, and action capsules.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add top-header',
    features: ['Translucent obsidian blur', 'Integrated search trigger', 'Theme switcher integration'],
    usageSnippet: `import { TopHeader } from "@99/ui"\n\n<TopHeader onOpenSearch={() => openCmd()} />`,
    codeSnippet: `export const TopHeader = ({ onOpenSearch }) => <header>...</header>;`,
    props: [{ name: 'onOpenSearch', type: '() => void', description: 'Command launcher trigger.' }],
  },
  {
    id: 'linear-issue-tracker',
    name: 'linear-issue-tracker',
    title: 'Linear Issue Tracker',
    description: 'Full-featured issue management workflow module with keyboard hotkeys, priority badges, and cycles.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add linear-issue-tracker',
    features: ['Keyboard navigation (J/K/C)', 'Priority badge indicators', 'Cycle progress bar'],
    usageSnippet: `import { LinearIssueTracker } from "@99/ui"\n\n<LinearIssueTracker />`,
    codeSnippet: `export const LinearIssueTracker = () => <div>...</div>;`,
    props: [],
  },
  {
    id: 'terminal-emulator',
    name: 'terminal-emulator',
    title: 'Terminal Emulator',
    description: 'Interactive CLI command execution terminal with colored status logs and monospaced font.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add terminal-emulator',
    features: ['Command execution simulation', 'Colored stdout/stderr logs', 'One-click copy command'],
    usageSnippet: `import { TerminalEmulator } from "@99/ui"\n\n<TerminalEmulator initialLogs={logs} />`,
    codeSnippet: `export const TerminalEmulator = ({ initialLogs }) => <div>...</div>;`,
    props: [{ name: 'initialLogs', type: 'TerminalLog[]', description: 'Startup terminal logs.' }],
  },
  {
    id: 'activity-feed',
    name: 'activity-feed',
    title: 'Activity Feed',
    description: 'Chronological team activity log with user avatars, status badges, and relative timestamps.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add activity-feed',
    features: ['User avatar integration', 'Relative time formatting', 'Action type badges'],
    usageSnippet: `import { ActivityFeed } from "@99/ui"\n\n<ActivityFeed activities={list} />`,
    codeSnippet: `export const ActivityFeed = ({ activities }) => <div>...</div>;`,
    props: [{ name: 'activities', type: 'ActivityItem[]', description: 'Activity entries.' }],
  },
  {
    id: 'ui99-wordmark',
    name: 'ui99-wordmark',
    title: 'UI99 Wordmark',
    description: 'Official vector typography wordmark with dashed serif outline and specular brand logo.',
    category: 'Layout & Navigation',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add ui99-wordmark',
    features: ['Pure vector SVG representation', 'Specular highlight rim', 'Responsive scaling'],
    usageSnippet: `import { UI99Wordmark } from "@99/ui"\n\n<UI99Wordmark size="md" />`,
    codeSnippet: `export const UI99Wordmark = ({ size }) => <svg>...</svg>;`,
    props: [{ name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Wordmark scale.' }],
  },
  {
    id: 'split-button',
    name: 'split-button',
    title: 'Split Button',
    description: 'Primary button action combined with a chevron trigger and dropdown item list.',
    category: 'Actions',
    primitive: 'Native & Floating',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add split-button',
    features: ['Independent primary action', 'Integrated dropdown menu', 'Keyboard navigable'],
    usageSnippet: `import { SplitButton } from "@99/ui"\n\n<SplitButton label="Save Changes" onClick={handleSave} items={[{ label: 'Save & Publish', onClick: handlePublish }]} />`,
    codeSnippet: `import { SplitButton } from '@/components/ui/SplitButton';\n\nexport default function Demo() {\n  return (\n    <SplitButton\n      label="Deploy Production"\n      onClick={() => console.log('Deploy')}\n      items={[\n        { label: 'Deploy to Staging', onClick: () => {} },\n        { label: 'Create Pull Request', onClick: () => {} },\n      ]}\n    />\n  );\n}`,
    props: [
      { name: 'label', type: 'string', description: 'Main button label.' },
      { name: 'onClick', type: '() => void', description: 'Primary action handler.' },
      { name: 'items', type: 'SplitButtonItem[]', description: 'Dropdown menu items.' },
    ],
  },
  {
    id: 'floating-action-button',
    name: 'floating-action-button',
    title: 'Floating Action Button (FAB)',
    description: 'Promoted circular or capsule action button with diffuse ambient shadow.',
    category: 'Actions',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add floating-action-button',
    features: ['Circular & expanded capsule modes', 'Velvet ambient diffusion', 'Mobile tactile tap target'],
    usageSnippet: `import { FloatingActionButton } from "@99/ui"\n\n<FloatingActionButton label="Create Issue" onClick={handleCreate} />`,
    codeSnippet: `import { FloatingActionButton } from '@/components/ui/FloatingActionButton';\n\nexport default function Demo() {\n  return <FloatingActionButton label="New Object" onClick={() => {}} />;\n}`,
    props: [
      { name: 'label', type: 'string', description: 'Optional expanded label.' },
      { name: 'icon', type: 'ReactNode', description: 'Trigger icon.' },
      { name: 'variant', type: "'primary' | 'emerald' | 'secondary'", default: "'primary'", description: 'Color theme.' },
    ],
  },
  {
    id: 'link-button',
    name: 'link-button',
    title: 'Link Button',
    description: 'Semantic hyperlink styled with micro-interaction hover underline and external indicator.',
    category: 'Actions',
    primitive: 'Native <a>',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add link-button',
    features: ['External link indicator', 'Subtle & emerald variants', 'Keyboard focus ring'],
    usageSnippet: `import { LinkButton } from "@99/ui"\n\n<LinkButton href="/docs" external>View Documentation</LinkButton>`,
    codeSnippet: `import { LinkButton } from '@/components/ui/LinkButton';\n\nexport default function Demo() {\n  return <LinkButton href="https://github.com" external>GitHub Repo</LinkButton>;\n}`,
    props: [
      { name: 'href', type: 'string', description: 'Destination URL.' },
      { name: 'external', type: 'boolean', default: 'false', description: 'Opens in new tab safely.' },
    ],
  },
  {
    id: 'dropdown-button',
    name: 'dropdown-button',
    title: 'Dropdown Button',
    description: 'Action trigger that reveals a selectable list of options in an obsidian overlay.',
    category: 'Actions',
    primitive: 'Native & Floating',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add dropdown-button',
    features: ['Selected indicator dot', 'Custom item icons', 'Click outside auto-dismiss'],
    usageSnippet: `import { DropdownButton } from "@99/ui"\n\n<DropdownButton label="Select Environment" options={options} onSelect={setEnv} />`,
    codeSnippet: `import { DropdownButton } from '@/components/ui/DropdownButton';\n\nexport default function Demo() {\n  return <DropdownButton label="Environment" options={[{ value: 'prod', label: 'Production' }]} onSelect={() => {}} />;\n}`,
    props: [
      { name: 'label', type: 'string', description: 'Placeholder label.' },
      { name: 'options', type: 'DropdownButtonOption[]', description: 'Options list.' },
    ],
  },
  {
    id: 'pin-input',
    name: 'pin-input',
    title: 'Pin Input',
    description: 'Masked numeric security pin input with automatic focus progression.',
    category: 'Forms',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add pin-input',
    features: ['Password bullet masking', 'Auto-advance on keypress', 'Paste support'],
    usageSnippet: `import { PinInput } from "@99/ui"\n\n<PinInput length={6} value={pin} onChange={setPin} />`,
    codeSnippet: `import { PinInput } from '@/components/ui/PinInput';\n\nexport default function Demo() {\n  return <PinInput length={4} value="1234" onChange={() => {}} />;\n}`,
    props: [
      { name: 'length', type: 'number', default: '6', description: 'Number of pin digits.' },
      { name: 'mask', type: 'boolean', default: 'true', description: 'Mask inputs with bullets.' },
    ],
  },
  {
    id: 'currency-input',
    name: 'currency-input',
    title: 'Currency Input',
    description: 'Formatted monetary input with prefix currency symbol and numeric validation.',
    category: 'Forms',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add currency-input',
    features: ['Symbol prefix & currency code', 'Decimal formatting', 'Min/Max constraints'],
    usageSnippet: `import { CurrencyInput } from "@99/ui"\n\n<CurrencyInput value={price} onChange={setPrice} currency="USD" />`,
    codeSnippet: `import { CurrencyInput } from '@/components/ui/CurrencyInput';\n\nexport default function Demo() {\n  return <CurrencyInput value={199.99} onChange={() => {}} />;\n}`,
    props: [
      { name: 'value', type: 'number', description: 'Monetary value.' },
      { name: 'currency', type: 'string', default: "'USD'", description: 'ISO currency code.' },
    ],
  },
  {
    id: 'date-range-picker',
    name: 'date-range-picker',
    title: 'Date Range Picker',
    description: 'Dual-date selector with start/end bounds and sprint range presets.',
    category: 'Forms',
    primitive: 'Native & Calendar',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add date-range-picker',
    features: ['Start and End date binding', 'Popup range selector', 'Validation against past dates'],
    usageSnippet: `import { DateRangePicker } from "@99/ui"\n\n<DateRangePicker startDate="2026-09-01" endDate="2026-09-30" onChange={setRange} />`,
    codeSnippet: `import { DateRangePicker } from '@/components/ui/DateRangePicker';\n\nexport default function Demo() {\n  return <DateRangePicker startDate="2026-09-01" endDate="2026-09-30" />;\n}`,
    props: [
      { name: 'startDate', type: 'string', description: 'ISO start date string.' },
      { name: 'endDate', type: 'string', description: 'ISO end date string.' },
    ],
  },
  {
    id: 'range-slider',
    name: 'range-slider',
    title: 'Range Slider',
    description: 'Dual-thumb slider track for selecting bounded continuous numeric intervals.',
    category: 'Forms',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add range-slider',
    features: ['Dual independent thumbs', 'Specular track highlighting', 'Touch and mouse dragging'],
    usageSnippet: `import { RangeSlider } from "@99/ui"\n\n<RangeSlider value={[20, 80]} onChange={setInterval} />`,
    codeSnippet: `import { RangeSlider } from '@/components/ui/RangeSlider';\n\nexport default function Demo() {\n  return <RangeSlider value={[10, 90]} min={0} max={100} onChange={() => {}} />;\n}`,
    props: [
      { name: 'value', type: '[number, number]', description: 'Current [min, max] values.' },
      { name: 'min', type: 'number', default: '0', description: 'Lower bound.' },
      { name: 'max', type: 'number', default: '100', description: 'Upper bound.' },
    ],
  },
  {
    id: 'checkbox-group',
    name: 'checkbox-group',
    title: 'Checkbox Group',
    description: 'Managed group of multi-select checkboxes with descriptions and orientations.',
    category: 'Forms',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add checkbox-group',
    features: ['Vertical and horizontal layout', 'Sub-labels and descriptions', 'Batch selection control'],
    usageSnippet: `import { CheckboxGroup } from "@99/ui"\n\n<CheckboxGroup options={options} value={selected} onChange={setSelected} />`,
    codeSnippet: `import { CheckboxGroup } from '@/components/ui/CheckboxGroup';\n\nexport default function Demo() {\n  return <CheckboxGroup options={[{ value: 'a', label: 'Option A' }]} value={['a']} onChange={() => {}} />;\n}`,
    props: [
      { name: 'options', type: 'CheckboxGroupOption[]', description: 'Group options.' },
      { name: 'value', type: 'string[]', description: 'Selected option values.' },
    ],
  },
  {
    id: 'data-table',
    name: 'data-table',
    title: 'Data Table',
    description: 'Full-featured enterprise table with instant search filter, column sorting, and pagination.',
    category: 'Data Display',
    primitive: 'Native <table>',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add data-table',
    features: ['Integrated search filter', 'Ascending/descending sort', 'Client-side pagination'],
    usageSnippet: `import { DataTable } from "@99/ui"\n\n<DataTable columns={columns} data={records} pageSize={10} />`,
    codeSnippet: `import { DataTable } from '@/components/ui/DataTable';\n\nexport default function Demo() {\n  return <DataTable columns={[{ key: 'name', header: 'Name', sortable: true }]} data={[{ name: 'Item 1' }]} />;\n}`,
    props: [
      { name: 'columns', type: 'DataTableColumn<T>[]', description: 'Column schemas.' },
      { name: 'data', type: 'T[]', description: 'Data rows.' },
    ],
  },
  {
    id: 'metric-card',
    name: 'metric-card',
    title: 'Metric Card',
    description: 'Executive KPI tile featuring delta badge, trend indicator, and sparkline graph.',
    category: 'Data Display',
    primitive: 'Native',
    version: '1.0.0',
    dependencies: [],
    cliCommand: 'npx @99/ui add metric-card',
    features: ['Trend percentage delta', 'Integrated SVG sparkline', 'Obsidian velvet card surface'],
    usageSnippet: `import { MetricCard } from "@99/ui"\n\n<MetricCard label="Monthly Recurring Revenue" value="$48,920" delta={14.8} sparklineData={[20, 30, 45, 60, 80]} />`,
    codeSnippet: `import { MetricCard } from '@/components/ui/MetricCard';\n\nexport default function Demo() {\n  return <MetricCard label="Active Users" value="9,942" delta={12.4} />;\n}`,
    props: [
      { name: 'label', type: 'string', description: 'KPI title.' },
      { name: 'value', type: 'string | number', description: 'Formatted metric.' },
      { name: 'delta', type: 'number', description: 'Percentage change.' },
    ],
  },
  {
    id: 'spinner',
    name: 'spinner',
    title: 'Spinner',
    description: 'Animated high-precision circular loader with subtle track and emerald variants.',
    category: 'Data Display',
    primitive: 'Native SVG',
    version: '1.0.0',
    dependencies: ['lucide-react'],
    cliCommand: 'npx @99/ui add spinner',
    features: ['Hardware-accelerated rotation', 'Emerald and subtle variants', 'Optional loading label'],
    usageSnippet: `import { Spinner } from "@99/ui"\n\n<Spinner size="md" variant="emerald" label="Syncing..." />`,
    codeSnippet: `import { Spinner } from '@/components/ui/Spinner';\n\nexport default function Demo() {\n  return <Spinner size="md" variant="emerald" label="Processing..." />;\n}`,
    props: [
      { name: 'size', type: "'xs' | 'sm' | 'md' | 'lg'", default: "'md'", description: 'Spinner dimension.' },
      { name: 'variant', type: "'emerald' | 'subtle' | 'white'", default: "'emerald'", description: 'Color style.' },
    ],
  },
];
