/**
 * UI99 Kit CSS artifacts — Phase 2.2
 * ui99.css (src/styles/ui99.css) is the single source of truth and is copied
 * verbatim into the package. `dark.css` / `light.css` are GENERATED entries:
 * they re-emit the corresponding theme block under `:root` so hosts that
 * never toggle a theme class still get real token values (no-JS default).
 * Extraction happens at build time — nothing is duplicated by hand.
 *
 * Run: bun run lib:css   (invoked by lib:build)
 */
import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'dist-kit');
mkdirSync(outDir, { recursive: true });

const banner = (title) =>
  `/*!\n * UI99 (@99/ui) — ${title}\n * GENERATED by scripts/build-kit-css.mjs from src/styles/ui99.css — DO NOT EDIT.\n * Regenerate: bun run lib:build\n */\n`;

/** Extract the declaration body of a `.scope { ... }` block from ui99.css. */
function extractBlock(css, scopeSelector) {
  const idx = css.indexOf(`${scopeSelector} {`);
  if (idx === -1) throw new Error(`Block not found in ui99.css: ${scopeSelector}`);
  const open = css.indexOf('{', idx);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === '{') depth++;
    if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(open + 1, i).trim();
    }
  }
  throw new Error(`Unbalanced braces in ui99.css block: ${scopeSelector}`);
}

const ui99Css = readFileSync(resolve(root, 'src/styles/ui99.css'), 'utf8');

// 1) Verbatim token stylesheet (single source of truth)
copyFileSync(resolve(root, 'src/styles/ui99.css'), resolve(outDir, 'ui99.css'));
copyFileSync(resolve(root, 'src/styles/porcelain.css'), resolve(outDir, 'porcelain.css'));

// 2) No-JS theme entries: re-emit the theme block under :root (generated, not hand-copied)
const darkBody = extractBlock(ui99Css, '.dark');
const lightBody = extractBlock(ui99Css, '.light');
const sharedBody = extractBlock(ui99Css, '.dark,\n.light');
const focusAndMotion = ui99Css
  .slice(ui99Css.indexOf('/* ======================= FOCUS UTILITIES'));

writeFileSync(
  resolve(outDir, 'dark.css'),
  `${banner('dark theme entry (no-JS default)')}\n@import "./ui99.css";\n\n/* Pre-activate obsidian dark tokens for hosts that never toggle a theme class. */\n:root {\n${darkBody}\n}\n\n${focusAndMotion}\n`,
);

writeFileSync(
  resolve(outDir, 'light.css'),
  `${banner('light theme entry (no-JS default)')}\n@import "./ui99.css";\n\n/* Pre-activate porcelain light tokens for hosts that never toggle a theme class. */\n:root {\n${lightBody}\n}\n\n${focusAndMotion}\n`,
);

console.log('[kit-css] ui99.css + porcelain.css + dark.css + light.css generated in dist-kit/');
console.log(`[kit-css] dark tokens: ${darkBody.split('\n').length} lines, shared: ${sharedBody.split('\n').length} lines`);
