/**
 * UI99 Kit CSS artifacts — Phase 2.2
 * ui99.css (src/styles/ui99.css) is the single source of truth and is copied
 * verbatim into the package. `dark.css` / `light.css` are GENERATED entries:
 * they re-emit the corresponding theme block under `:root` so hosts that
 * never toggle a theme class still get real token values (no-JS default).
 * Extraction happens at build time — nothing is duplicated by hand.
 *
 * Run: bun run lib:css   (invoked by lib:build)
 */
import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'dist-kit');
mkdirSync(outDir, { recursive: true });

const banner = (title) =>
  `/*!\n * UI99 (@99/ui) — ${title}\n * GENERATED by scripts/build-kit-css.mjs from src/styles/ui99.css — DO NOT EDIT.\n * Regenerate: bun run lib:build\n */\n`;

/**
 * Extract the declaration body of a scope block from ui99.css.
 * Matches the FIRST `{` after the selector (the selector may span multiple
 * lines, e.g. `[data-theme='light'],\n.light {`), so no newline guessing.
 */
function extractBlock(css, scopeSelector) {
  const idx = css.indexOf(scopeSelector);
  if (idx === -1) throw new Error(`Block not found in ui99.css: ${scopeSelector}`);
  const open = css.indexOf('{', idx);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === '{') depth++;
    if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(open + 1, i).trim();
    }
  }
  throw new Error(`Unbalanced braces in ui99.css block: ${scopeSelector}`);
}

const ui99Css = readFileSync(resolve(root, 'src/styles/ui99.css'), 'utf8');
const elevationCss = readFileSync(resolve(root, 'src/styles/ui99-elevation.css'), 'utf8');
const glowCss = readFileSync(resolve(root, 'src/styles/ui99-glow.css'), 'utf8');
const typeCss = readFileSync(resolve(root, 'src/styles/ui99-type.css'), 'utf8');
const typeUtilsCss = readFileSync(resolve(root, 'src/styles/ui99-type-utilities.css'), 'utf8');

// 1) Verbatim token stylesheets (single source of truth).
// The structural and glow layers are part of the published token contract —
// consumers get elevation/radius/spacing/blur/glow without importing app CSS.
copyFileSync(resolve(root, 'src/styles/ui99.css'), resolve(outDir, 'ui99.css'));
copyFileSync(
  resolve(root, 'src/styles/ui99-elevation.css'),
  resolve(outDir, 'ui99-elevation.css'),
);
copyFileSync(resolve(root, 'src/styles/ui99-glow.css'), resolve(outDir, 'ui99-glow.css'));
copyFileSync(resolve(root, 'src/styles/ui99-type.css'), resolve(outDir, 'ui99-type.css'));
copyFileSync(
  resolve(root, 'src/styles/ui99-type-utilities.css'),
  resolve(outDir, 'ui99-type-utilities.css'),
);
copyFileSync(resolve(root, 'src/styles/porcelain.css'), resolve(outDir, 'porcelain.css'));
// Tailwind v4 semantic-class layer (daisyUI-class gateway, audit P2.7)
copyFileSync(resolve(root, 'src/tailwind/ui99-plugin.css'), resolve(outDir, 'tailwind.css'));

// 1b) styles.css — the single entry consumers import. Must pull in every layer,
// or `shadow-(--elevation-3)` silently resolves to nothing for npm users.
writeFileSync(
  resolve(outDir, 'styles.css'),
  `${banner('public token entry point')}\n@import "./ui99.css";\n@import "./ui99-elevation.css";\n@import "./ui99-glow.css";\n@import "./ui99-type.css";\n\n/* No-JS default theme. Hosts that toggle .dark/.light ignore these. */\n${extractBlock(ui99Css, '.dark,')}\n\n/* The .type-* / .icon-* utility classes live in a separate file so consumers\n   who only want tokens (no utilities) can skip them. */\n@import "./ui99-type-utilities.css";\n`,
);

// 2) No-JS theme entries: re-emit the theme block under :root (generated, not hand-copied)
// NOTE: ui99.css scopes themes via .dark/.light AND the data-theme attribute
// (audit P2.8); the class selectors are still present and used for extraction.
const darkBody = extractBlock(ui99Css, '.dark,');
const lightBody = extractBlock(ui99Css, "[data-theme='light'],");
// The shared scope spans multiple selector lines; match its final line only.
const sharedBody = extractBlock(ui99Css, '[data-theme] {');
const focusAndMotion = ui99Css
  .slice(ui99Css.indexOf('/* ======================= FOCUS UTILITIES'));

writeFileSync(
  resolve(outDir, 'dark.css'),
  `${banner('dark theme entry (no-JS default)')}\n@import "./styles.css";\n\n/* Pre-activate obsidian dark tokens for hosts that never toggle a theme class. */\n:root {\n${darkBody}\n}\n\n${focusAndMotion}\n`,
);

writeFileSync(
  resolve(outDir, 'light.css'),
  `${banner('light theme entry (no-JS default)')}\n@import "./styles.css";\n\n/* Pre-activate porcelain light tokens for hosts that never toggle a theme class. */\n:root {\n${lightBody}\n}\n\n${focusAndMotion}\n`,
);

console.log(
  '[kit-css] styles.css + ui99.css + ui99-elevation.css + ui99-glow.css + ui99-type.css + ui99-type-utilities.css + porcelain.css + dark.css + light.css generated in dist-kit/',
);
console.log(`[kit-css] dark tokens: ${darkBody.split('\n').length} lines, shared: ${sharedBody.split('\n').length} lines`);
